added semantic description to social.media page
shesharpnl/knowledge-hub pull request #31
Opened 2023-10-08 22:58 UTC by charlieintech

## Description

## Type of PR

- [ ] ✨ Feature
- [ ] 🐞 Bug fix
- [ X] 📄 Documentation update
- [ ] Others

## Related Issue

2023-10-09 05:01 UTC, mariahlaqua requested changes
Hi @charlieintech ! Thanks for your contribution. Can you update the description:

- remove // from beginning
- mention SheSharp (e.g. "A place for SheSharp community members to share their social media links")
- maybe include a link to join our Slack (https://shesharp.co/slack) in the description, or a section for SheSharp socials with the website and Slack.

Let me know if you need further input. Thanks so much for contributing to our project!

2023-10-09 05:05 UTC, mariahlaqua commented
Also hi @charlieintech ! I did #100Devs cohort two! nice to see another 100Devs-er here!!

2023-10-09 18:32 UTC, charlieintech commented
> Hi @charlieintech ! Thanks for your contribution. Can you update the description:
> 
> * remove // from beginning
> * mention SheSharp (e.g. "A place for SheSharp community members to share their social media links")
> * maybe include a link to join our Slack (https://shesharp.co/slack) in the description, or a section for SheSharp socials with the website and Slack (this is an extra bonus and not required if you would just like it approved )
> 
> Let me know if you need further input. Thanks so much for contributing to our project!

Hi! I made changes and pushed the changes. Please let me know if I need to make any corrections.

2023-10-09 22:12 UTC, adiati98 requested changes
@charlieintech I left here some feedback 🙂

2023-10-09 22:12 UTC, adiati98 commented on socials/socials.md
> +- [SheSharp] (https://www.shesharp.co/new-in-tech-scholarship)
```suggestion
### Join SheSharp Community

Join our community on [Slack](https://shesharp.co/slack)!

For more information about our community, visit [our website](https://www.shesharp.co/).
```

2023-10-09 23:59 UTC, charlieintech commented
Thanks for the help :) I think I updated it. Please let me know if there is anything else.

2023-10-10 08:04 UTC, mariahlaqua requested changes
`
Come and join out community on [Slack] (https://shesharp.co/slack)`

Can we fix this typo as well? Thanks again @charlieintech !!

`
Come and join our community on [Slack] (https://shesharp.co/slack)`

2023-10-10 12:32 UTC, charlieintech commented
Fixed typo :)

2023-10-10 22:37 UTC, mariahlaqua commented
Thank you @charlieintech ! 💯

2023-10-10 22:37 UTC, merged